name: resAb
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - annotated-types=0.6.0=py314h06a4308_1
  - anyio=4.10.0=py314h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2026.01.04=py314h06a4308_0
  - click=8.2.1=py314h06a4308_1
  - distro=1.9.0=py314h06a4308_0
  - h11=0.16.0=py314h06a4308_1
  - httpcore=1.0.9=py314h06a4308_0
  - httpx=0.28.1=py314h06a4308_1
  - idna=3.11=py314h06a4308_0
  - jiter=0.12.0=py314h498d7c9_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.5=h7934f7d_0
  - openai=2.14.0=py314h06a4308_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyh0d26453_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pydantic=2.12.4=py314h06a4308_0
  - pydantic-core=2.41.5=py314h498d7c9_1
  - python=3.14.2=h90eec9f_101_cp314
  - python-dotenv=1.1.0=py314h06a4308_0
  - python_abi=3.14=2_cp314
  - readline=8.3=hc2a1206_0
  - sniffio=1.3.1=py314h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=py314h6fa48dc_1
  - typing-extensions=4.15.0=py314h06a4308_0
  - typing-inspection=0.4.2=py314h06a4308_0
  - typing_extensions=4.15.0=py314h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
prefix: /home/marco/miniconda3/envs/resAb
